language: java
env:
    global:
        - MAVEN_OPTS="-Xmx2g"
branches:
    only:
        - develop
        - master
before_install:
    - curl -O http://www.anc.org/tools/settings.xml
    - curl -O http://downloads.lappsgrid.org/standford-models.tgz
    - if [ ! which tar ] ; then apt-get install -y tar ; fi
    - tar xzf stanford-models.tgz
    - sudo mkdir -p /usr/share/lapps/
    - mv stanford /usr/share/lapps
    - sudo chmod -R +r /usr/share/lapps
install:
    - mvn anc:version --settings settings.xml
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings settings.xml
script:
    - mvn clean --settings settings.xml
    - mvn compile --settings settings.xml
    - mvn test --settings settings.xml
